package view;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import java.awt.*; 

public class AfficherRetardMoisView extends javax.swing.JFrame {

    /**
     * Creates new form AfficherRetardView
     */
    public AfficherRetardMoisView() {
        initComponents();
        
        initView(); 
        
        ImageIcon img = new ImageIcon(getClass().getResource("/ressources/icon.png"));
        setIconImage(img.getImage());
        
        setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")                        
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        tblRetard = new javax.swing.JTable();
        btnEnvRelance = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Des Retards - 1 Mois");


        tblRetardModel = new DefaultTableModel(
                new Object [][] {
                },
                new String [] {
                    "CIN", "Identifiant d'emprunt", "Date d'emprunt"
                }
        		); 
        
        tblRetard.setModel(tblRetardModel);
        
        scrollPane.setViewportView(tblRetard);

        btnEnvRelance.setText("Declarer perdu");
        btnEnvRelance.setMnemonic('D');

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnvRelance, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnvRelance)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    private void initView( ) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfficherRetardJrsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfficherRetardJrsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfficherRetardJrsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfficherRetardJrsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    	
    }

	public javax.swing.JButton getBtnEnvRelance() {
		return btnEnvRelance;
	}

	public javax.swing.JScrollPane getScrollPane() {
		return scrollPane;
	}

	public javax.swing.JTable getTblRetard() {
		return tblRetard;
	}

	public DefaultTableModel getTblRetardModel() {
		return tblRetardModel;
	}

	
    private javax.swing.JButton btnEnvRelance;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblRetard;
    private DefaultTableModel tblRetardModel;   
    
	public void showMessage(String msj, String title, int informationMessage) {
		
		JOptionPane.showMessageDialog(this, msj, title, informationMessage);
		
	}

	public void triggerErrorMessage(String msj, String title, int errorMessage) {
		
		JOptionPane.showMessageDialog(this, msj, title, errorMessage);
		
	}
}
