package view;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import java.awt.*;

public class ConsulterEtudiantView extends javax.swing.JFrame {

    /**
     * Creates new form ConsulterLivresView
     */
    public ConsulterEtudiantView() {
        
    	initComponents();
        
        initView(); 
        
        ImageIcon img = new ImageIcon(getClass().getResource("/ressources/icon.png"));
        setIconImage(img.getImage());
        
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        
        btnModifier.setVisible(false) ; 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tblPanel = new javax.swing.JPanel();
        jScrollPaneTbl = new javax.swing.JScrollPane();
        tblEtudiant = new javax.swing.JTable();
        btnModifier = new javax.swing.JButton();
        btnSuprimer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultation Des Etudiants");
        
        tblModel = new DefaultTableModel(
                new Object [][] {
                },
                new String [] {
                    "CNE", "Nom", "Prenom", "Adresse"
                }
        		); 
        
        tblEtudiant.setModel(tblModel);
        jScrollPaneTbl.setViewportView(tblEtudiant);

        javax.swing.GroupLayout tblPanelLayout = new javax.swing.GroupLayout(tblPanel);
        tblPanel.setLayout(tblPanelLayout);
        tblPanelLayout.setHorizontalGroup(
            tblPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneTbl, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        tblPanelLayout.setVerticalGroup(
            tblPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblPanelLayout.createSequentialGroup()
                .addComponent(jScrollPaneTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnModifier.setMnemonic('M');
        btnModifier.setText("Modifier");

        btnSuprimer.setMnemonic('R');
        btnSuprimer.setText("Retour");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSuprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModifier))
                    .addComponent(tblPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tblPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifier)
                    .addComponent(btnSuprimer))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public void initView( ) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsulterEtudiantView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsulterEtudiantView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsulterEtudiantView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsulterEtudiantView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }
    
    
    
    public javax.swing.JButton getBtnModifier() {
		return btnModifier;
	}

	public javax.swing.JButton getBtnSuprimer() {
		return btnSuprimer;
	}

	public javax.swing.JScrollPane getjScrollPaneTbl() {
		return jScrollPaneTbl;
	}

	public javax.swing.JTable getTblEtudiant() {
		return tblEtudiant;
	}

	public DefaultTableModel getTblModel() {
		return tblModel;
	}

	public javax.swing.JPanel getTblPanel() {
		return tblPanel;
	}



	// Variables declaration - do not modify                     
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSuprimer;
    private javax.swing.JScrollPane jScrollPaneTbl;
    private javax.swing.JTable tblEtudiant;
    private DefaultTableModel tblModel; 
    private javax.swing.JPanel tblPanel;
    // End of variables declaration 

    
	public void showMessage(String msj, String title) {
		
		JOptionPane.showMessageDialog(this, msj, title, JOptionPane.INFORMATION_MESSAGE);
		
	}

	public void triggerErrorMessage(String msj, String title) {
		
		JOptionPane.showMessageDialog(this, msj, title, JOptionPane.ERROR_MESSAGE);
		
	}

	public int ConfermToDelete(String msj, String title) {
		
		return JOptionPane.showConfirmDialog(this, msj, title, JOptionPane.YES_NO_OPTION);
	
	}
}
