/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import java.awt.*; 

public class VerifierExemplaireEnCoursView extends javax.swing.JFrame {

    /**
     * Creates new form EnregisterEmprunteView
     */
    public VerifierExemplaireEnCoursView() {
        
    	initComponents();
    	
    	initView();
        
        setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	  pnlEnrEmprunt = new javax.swing.JPanel();
          lblCin = new javax.swing.JLabel();
          txtCin = new javax.swing.JTextField();
          btnSearch = new javax.swing.JButton();
          tblScrollPane = new javax.swing.JScrollPane();
          tblEmprunt = new javax.swing.JTable();
          lblNbrEmpruntEnCours = new javax.swing.JLabel();
          lblNbrEmprunt = new javax.swing.JLabel();
          btnAnnuler = new javax.swing.JButton();
          btnContinuer = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setTitle("Verifier nombre d'emprunt en cours");

          lblCin.setText("CIN");

          txtCin.setMaximumSize(new java.awt.Dimension(88, 22));
          txtCin.setMinimumSize(new java.awt.Dimension(88, 22));

          btnSearch.setText("Rechercher");
          
          empruntDefaultModel = new DefaultTableModel(
        new Object [][] {
        	  
          },
          new String [] {
              "Nom", "Prenom", "Emprunt"
          }); 
                  
//          tblEmprunt.setModel(new javax.swing.table.DefaultTableModel(
//              new Object [][] {
//            	  
//              },
//              new String [] {
//                  "Nom", "Prenom", "Emprunt"
//              }
//          ) {
//              boolean[] canEdit = new boolean [] {
//                  false, false, false
//              };
//
//              public boolean isCellEditable(int rowIndex, int columnIndex) {
//                  return canEdit [columnIndex];
//              }
//          });
          
          tblEmprunt.setModel(empruntDefaultModel); 
          
          tblScrollPane.setViewportView(tblEmprunt);

          lblNbrEmpruntEnCours.setText("Nombre D'emprunt en cours :");

          lblNbrEmprunt.setText("0");

          btnAnnuler.setText("Annuler");

          btnContinuer.setMnemonic('C');
          btnContinuer.setText("Continuer");
          btnContinuer.setEnabled(false);

          javax.swing.GroupLayout pnlEnrEmpruntLayout = new javax.swing.GroupLayout(pnlEnrEmprunt);
          pnlEnrEmprunt.setLayout(pnlEnrEmpruntLayout);
          pnlEnrEmpruntLayout.setHorizontalGroup(
              pnlEnrEmpruntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(pnlEnrEmpruntLayout.createSequentialGroup()
                  .addGap(71, 71, 71)
                  .addGroup(pnlEnrEmpruntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(tblScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                      .addGroup(pnlEnrEmpruntLayout.createSequentialGroup()
                          .addComponent(lblCin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(txtCin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(btnSearch)))
                  .addContainerGap(72, Short.MAX_VALUE))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnrEmpruntLayout.createSequentialGroup()
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(pnlEnrEmpruntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnrEmpruntLayout.createSequentialGroup()
                          .addComponent(lblNbrEmpruntEnCours)
                          .addGap(48, 48, 48)
                          .addComponent(lblNbrEmprunt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addGap(37, 37, 37))
                      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnrEmpruntLayout.createSequentialGroup()
                          .addComponent(btnContinuer)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(btnAnnuler)
                          .addGap(74, 74, 74))))
          );
          pnlEnrEmpruntLayout.setVerticalGroup(
              pnlEnrEmpruntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(pnlEnrEmpruntLayout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(pnlEnrEmpruntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                      .addComponent(lblCin)
                      .addComponent(txtCin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(btnSearch))
                  .addGap(33, 33, 33)
                  .addComponent(tblScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(33, 33, 33)
                  .addGroup(pnlEnrEmpruntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                      .addComponent(lblNbrEmprunt)
                      .addComponent(lblNbrEmpruntEnCours))
                  .addGap(30, 30, 30)
                  .addGroup(pnlEnrEmpruntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                      .addComponent(btnContinuer)
                      .addComponent(btnAnnuler))
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                  .addGap(29, 29, 29)
                  .addComponent(pnlEnrEmprunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addContainerGap(22, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                  .addGap(36, 36, 36)
                  .addComponent(pnlEnrEmprunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addContainerGap(37, Short.MAX_VALUE))
          );

          pack();
    }                   

    
    private void initView() {
    	

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerifierExemplaireEnCoursView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerifierExemplaireEnCoursView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerifierExemplaireEnCoursView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerifierExemplaireEnCoursView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    	
    }
    
    
    public JButton getBtnContinuer() {
    	
    	return btnContinuer; 
    	
    }
    
    public JButton getBtnAnnuler() {
    	return btnAnnuler; 
    }
    
    public JButton getBtnSearch() {
    	
    	return btnSearch; 
    	
    }
    
    public JTextField getTxtCin() {
    	return txtCin; 
    }
    
    public DefaultTableModel getEmpruntDefaultModel() { 
    	return empruntDefaultModel; 
    }
    
    public JLabel getLblNbrEmprunt() {
    	return lblNbrEmprunt; 
    }
    
    // Variable Declaration start
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnContinuer;
    private javax.swing.JLabel lblCin;
    private javax.swing.JLabel lblNbrEmprunt;
    private javax.swing.JLabel lblNbrEmpruntEnCours;
    private javax.swing.JPanel pnlEnrEmprunt;
    private javax.swing.JTable tblEmprunt;
    private DefaultTableModel empruntDefaultModel; 
    private javax.swing.JScrollPane tblScrollPane;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField txtCin;
    // End of variables declaration                   
}
